variables:
    VPC_NAME:
        required: true
        description: the name of the VPC
        default: test-vpc
    VPC_OCTETS:
        required: true
        description: the /16 net of the VPC to look for - i.e 10.11.0.0
        default: 10.11.0.0
    REGION:
        required: true
        description: use default except for multiple region use cases
        default: "PLAN::region"
        type: string
    VPC_TAGS:
        required: false
        description: tags to apply to the vpc
        type: array
        default:
    NEW_RVARD_1:
        required: true
        description: New required var with default
        default: "New Default"
    NEW_RVAR_2:
        required: true
        description: New required var with no default
